version: "2.1"

services:

  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 15s
      timeout: 3s
      retries: 8
    image: postgres:11.2-alpine
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data/

  python:
    build:
      context: .
    command: ["-m", "db"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - db
    volumes:
      - ./:/kannji/

volumes:
  db:

networks:
  db:

