version: "2.1"

services:

  db:
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_STORAGE_ENGINE=rocksdb
    image: arangodb:3.5.2
    networks:
      - db
    ports:
      - "8529:8529"
    volumes:
      - /var/lib/arangodb3

  python:
    build:
      context: .
    command: ["-m", "db"]
    environment:
      - DEBUG
    networks:
      - db
    volumes:
      - ./:/kannji/

volumes:
  db:

networks:
  db:

